#!/usr/bin/perl -w -- 
#
# generated by wxGlade 0.6.8 on Tue May 12 22:08:45 2015
#
# To get wxPerl visit http://wxPerl.sourceforge.net/
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

use Wx 0.15 qw[:allclasses];
use strict;

package MyApp;

use base qw(Wx::App);
use strict;
use MyFrame;


sub OnInit {
    my ($self) = shift;

    Wx::InitAllImageHandlers();

    my $GcodeTweaker = MyFrame->new();

    $self->SetTopWindow($GcodeTweaker);
    $GcodeTweaker->Show(1);

    return 1;
}

# end of class MyApp

package main;

unless (caller) {
    #my $local = Wx::Locale->new( "English", "en", "en" );    # replace with ??
    #$local->AddCatalog("gcode_tweaker")
    #  ;    # replace with the appropriate catalog name

    my $gcode_tweaker = MyApp->new();
    $gcode_tweaker->MainLoop();
}
